apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  #Selector used by Deployment how find all the pods it is going to create
  selector:
    matchLabels:
      app: tickets
  #Template is telling Deployment how to create each individual pods
  template:
    metadata:
      labels:
        app: tickets
    #Spec telling pods how to behave
    spec:
      containers:
        - name: tickets
          image: desmon91/tickets
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-srv:27017/tickets"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
#Service kind used to create a simple url so the pods can be communicated
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  #Selector here is telling Service how to find the pods name
  selector:
    app: tickets
  #Name here are for logging purposes
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
